# Generated by Django 2.1.7 on 2019-03-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Store', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Discount_Number', models.CharField(max_length=200)),
                ('Deadline', models.CharField(max_length=50)),
                ('Notice', models.CharField(max_length=200)),
            ],
        ),
    ]
