# Generated by Django 2.1.7 on 2019-03-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Discount',
        ),
    ]
